Import('env')

env.Append(CPPPATH=['/home/whosemario/workspace2/multithreadlib/net/'])
MyLibs= ['pthread','multithreads','net']

poll_test= env.Program('poll_test.cpp',LIBS=MyLibs)
timerfd_test= env.Program('timerfd_test.cpp',LIBS=MyLibs)

#install
InstallObj = [poll_test,
              timerfd_test
            ]
env.Install('#build/',InstallObj)
