Import('env')
#env.Append(CPPPATH=['/Users/whosemario/Workspaces/MultiThreadLib/common/include/'])
env.Append(LIBPATH=['/home/whosemario/workspace2/multithreadlib/net/'])

MyLibs= ['multithreads']
env.Library('net',Glob('*.cpp'),LIBS=MyLibs)

Export('env')
SConscript(['test/SConscript'])
